# Generated by Django 4.0.1 on 2023-07-20 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 2, 2, 760951))),
                ('prefix', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('isd_code', models.CharField(max_length=5)),
                ('mobile_no', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=25)),
                ('source_category', models.CharField(max_length=20)),
                ('preferred_location', models.CharField(max_length=25)),
                ('current_ctc', models.BigIntegerField()),
                ('expected_ctc', models.BigIntegerField()),
                ('notice_period', models.IntegerField()),
                ('skills', models.TextField(max_length=200)),
                ('remarks', models.TextField(max_length=200)),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('passport_no', models.CharField(max_length=9)),
                ('expiry_date', models.DateField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('contact_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=20)),
                ('current_address', models.TextField(max_length=250)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('pin_code', models.CharField(max_length=6)),
                ('assigned', models.BooleanField(default=False)),
                ('last5feedback', models.TextField()),
                ('next_interview', models.DateField(default=None)),
                ('knockout_score', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', models.CharField(max_length=25)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 2, 2, 767968))),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='C:\\Users\\anshu\\OneDrive\\Desktop\\Work\\test\\core\\files')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
    ]
