# Generated by Django 4.0.1 on 2023-07-20 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 8, 5, 359264)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 8, 5, 352767)),
        ),
    ]
