# Generated by Django 4.2.3 on 2023-07-23 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_position_candidate_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 0, 37, 57, 117784)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 0, 37, 57, 111758)),
        ),
    ]
