# Generated by Django 4.2.3 on 2023-07-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_Client',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_HRExec',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_HRManager',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_SuperAdmin',
        ),
        migrations.AddField(
            model_name='account',
            name='role_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
