# Generated by Django 4.0.1 on 2023-07-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_groups_alter_account_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role_id',
            field=models.IntegerField(default=1),
        ),
    ]
